version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-auth-app_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel-auth-app_db
    ports:
      - "4306:4306"
    environment:
      MYSQL_ROOT_PASSWORD: raji@2001
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: raji@2001
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
